baseURL = 'https://type.cyhsu.xyz/'
copyright = "© Platy Hsu"
defaultContentLanguage = 'zh-cn'
enableInlineShortcodes = true
hasCJKLanguage = true
languageCode = 'zh-cn'
paginate = 5
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "nord"
rssLimit = 20
summaryLength = 100
theme = 'nordic'
title = 'Neverland'

[params]
Toc = true
centerTheme = true
showLastUpdated = true
themeColor = 'blue'
toggle = true
updatedDatePrefix = "Updated"
[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/platyhsu"

[permalinks]
pages = '/:filename/'
posts = '/:year/:month/:filename/'

[[menu.main]]
name = "colophon"
url = "/colophon/"
weight = 1

[[menu.main]]
name = "archive"
url = "/posts/"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "readings"
url = "https://platylinks.substack.com"
weight = 10

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss+xml"
noUgly = true
